package telas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author comp16
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() throws SQLException {
        //this.cargas = new InternalCargas();
        initComponents();
    }

    private final InternalPedido pedido = new InternalPedido();
    private final InternalCargas cargas = new InternalCargas();
    private final InternalVisualizarCargas vizucargas = new InternalVisualizarCargas();
    private final InternalCadastroTransportador cadastrotransp = new InternalCadastroTransportador();
    private final InternalCadastroVeículos cadastroveiculos = new InternalCadastroVeículos();
    private final InternalNotaFiscal notafiscal = new InternalNotaFiscal();
    private final InternalRotas rotas = new InternalRotas();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        painelPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuFaturamento = new javax.swing.JMenu();
        menuNFeFaturamento = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuTransportadorCadastrar = new javax.swing.JMenuItem();
        menuVeiculosCadastrar = new javax.swing.JMenuItem();
        menuCargas = new javax.swing.JMenu();
        menuGerenciarCargas = new javax.swing.JMenuItem();
        menuVisualizarCargas = new javax.swing.JMenuItem();
        menuRotas = new javax.swing.JMenu();
        menuVisualizarRotas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo Expedição");

        painelPrincipal.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/truck-brown-icon.png"))); // NOI18N

        painelPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jLabel1)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        menuFaturamento.setText("Faturamento");

        menuNFeFaturamento.setText("Emissão de NFe");
        menuNFeFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNFeFaturamentoActionPerformed(evt);
            }
        });
        menuFaturamento.add(menuNFeFaturamento);

        barraMenu.add(menuFaturamento);

        menuCadastrar.setText("Cadastrar");

        menuTransportadorCadastrar.setText("Transportador");
        menuTransportadorCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransportadorCadastrarActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuTransportadorCadastrar);

        menuVeiculosCadastrar.setText("Veículos");
        menuVeiculosCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculosCadastrarActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuVeiculosCadastrar);

        barraMenu.add(menuCadastrar);

        menuCargas.setText("Cargas");

        menuGerenciarCargas.setText("Gerenciar");
        menuGerenciarCargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarCargasActionPerformed(evt);
            }
        });
        menuCargas.add(menuGerenciarCargas);

        menuVisualizarCargas.setText("Visualizar");
        menuVisualizarCargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisualizarCargasActionPerformed(evt);
            }
        });
        menuCargas.add(menuVisualizarCargas);

        barraMenu.add(menuCargas);

        menuRotas.setText("Rotas");

        menuVisualizarRotas.setText("Gerenciar");
        menuVisualizarRotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisualizarRotasActionPerformed(evt);
            }
        });
        menuRotas.add(menuVisualizarRotas);

        barraMenu.add(menuRotas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGerenciarCargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarCargasActionPerformed

    
        try {
            cargas.setarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        painelPrincipal.remove(cargas);
        painelPrincipal.add(cargas);
        cargas.setVisible(true);
        cargas.setPosicao();


    }//GEN-LAST:event_menuGerenciarCargasActionPerformed

    private void menuTransportadorCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransportadorCadastrarActionPerformed
        
        painelPrincipal.remove(cadastrotransp);
        painelPrincipal.add(cadastrotransp);
        cadastrotransp.setVisible(true);
        cadastrotransp.setPosicao();

        
    }//GEN-LAST:event_menuTransportadorCadastrarActionPerformed

    private void menuVeiculosCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculosCadastrarActionPerformed
        
        try {
            cadastroveiculos.setarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        painelPrincipal.remove(cadastroveiculos);
        painelPrincipal.add(cadastroveiculos);
        cadastroveiculos.setVisible(true);
        cadastroveiculos.setPosicao();
    }//GEN-LAST:event_menuVeiculosCadastrarActionPerformed

    private void menuNFeFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNFeFaturamentoActionPerformed

        try {
            notafiscal.setarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        painelPrincipal.remove(notafiscal);
        painelPrincipal.add(notafiscal);
        notafiscal.setVisible(true);
        notafiscal.setPosicao();
    }//GEN-LAST:event_menuNFeFaturamentoActionPerformed

    private void menuVisualizarRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisualizarRotasActionPerformed
        painelPrincipal.remove(rotas);
        painelPrincipal.add(rotas);
        
        try {
            rotas.setarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rotas.setVisible(true);
        rotas.setPosicao();
    }//GEN-LAST:event_menuVisualizarRotasActionPerformed

    private void menuVisualizarCargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisualizarCargasActionPerformed
        
        painelPrincipal.remove(vizucargas);
        painelPrincipal.add(vizucargas);
        
        try {
            vizucargas.setarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        vizucargas.setVisible(true);
        vizucargas.setPosicao();
        
    }//GEN-LAST:event_menuVisualizarCargasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FramePrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuCargas;
    private javax.swing.JMenu menuFaturamento;
    private javax.swing.JMenuItem menuGerenciarCargas;
    private javax.swing.JMenuItem menuNFeFaturamento;
    private javax.swing.JMenu menuRotas;
    private javax.swing.JMenuItem menuTransportadorCadastrar;
    private javax.swing.JMenuItem menuVeiculosCadastrar;
    private javax.swing.JMenuItem menuVisualizarCargas;
    private javax.swing.JMenuItem menuVisualizarRotas;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables

    private Object getDesktopPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
