package telas;

import dao.CargasDAO;
import gets_sets.CargasGetSet;
import gets_sets.NFeGetSet;
import gets_sets.RotasGetSet;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author comp16
 */
public class InternalCargas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalCargas
     */
    private CargasDAO cargasDAO = new CargasDAO();
    private DefaultTableModel modeloNFe, modeloCargas;
    private List<NFeGetSet> nfgetset;

    Vector itensCidades = cargasDAO.carregaCidadesCargas();
    Vector itensTransportador = cargasDAO.carregaFormaTransporte();

    public InternalCargas() throws SQLException {

        initComponents();

        setarCampos();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transporteComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cidadeComboBox = new javax.swing.JComboBox<>();
        botaoPesquisar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idCargaNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaoConfirmarCarga = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaCargas = new javax.swing.JTable();
        idRotaNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaNFRelacionada = new javax.swing.JTable();
        botaoBaixo = new javax.swing.JButton();
        botaoCima = new javax.swing.JButton();

        setClosable(true);

        transporteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        transporteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transporteComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Forma de Transporte");

        jLabel2.setText("NFe Relacionada");

        jLabel3.setText("Cidade");

        cidadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Carga");

        idCargaNum.setEditable(false);
        idCargaNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idCargaNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCargaNumActionPerformed(evt);
            }
        });

        jLabel5.setText("Itens da Carga");

        botaoConfirmarCarga.setText("Confirmar Carga");
        botaoConfirmarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCargaActionPerformed(evt);
            }
        });

        tabelaCargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NFe", "Cliente", "Rua", "Cidade", "Estado"
            }
        ));
        jScrollPane3.setViewportView(tabelaCargas);

        idRotaNum.setEditable(false);
        idRotaNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idRotaNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRotaNumActionPerformed(evt);
            }
        });

        jLabel7.setText("Rota");

        tabelaNFRelacionada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NFe", "Cliente", "Rua", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaNFRelacionada.getTableHeader().setReorderingAllowed(false);
        tabelaNFRelacionada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNFRelacionadaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaNFRelacionada);
        if (tabelaNFRelacionada.getColumnModel().getColumnCount() > 0) {
            tabelaNFRelacionada.getColumnModel().getColumn(0).setResizable(false);
            tabelaNFRelacionada.getColumnModel().getColumn(1).setResizable(false);
            tabelaNFRelacionada.getColumnModel().getColumn(2).setResizable(false);
            tabelaNFRelacionada.getColumnModel().getColumn(3).setResizable(false);
            tabelaNFRelacionada.getColumnModel().getColumn(4).setResizable(false);
        }

        botaoBaixo.setText("Subir");
        botaoBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBaixoActionPerformed(evt);
            }
        });

        botaoCima.setText("Descer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transporteComboBox, 0, 174, Short.MAX_VALUE)
                                    .addComponent(cidadeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoPesquisar)
                                    .addComponent(jLabel2))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCargaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idRotaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoCima, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoConfirmarCarga)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(transporteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botaoPesquisar)))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionar)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idCargaNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idRotaNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoBaixo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoConfirmarCarga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed

        try {

            String transporte = (String) transporteComboBox.getSelectedItem();
            String cidade = (String) cidadeComboBox.getSelectedItem();

            List<NFeGetSet> NFe = cargasDAO.getNFe(transporte, cidade);

            modeloNFe = (DefaultTableModel) tabelaNFRelacionada.getModel();
            modeloCargas = (DefaultTableModel) tabelaCargas.getModel();
            modeloNFe.setNumRows(0);

            for (int i = 0; i < NFe.size(); i++) {
                //boolean flag = true;
                //for (int j = 0; j < modeloCargas.getRowCount(); j++) {
                //  if (modeloCargas.getValueAt(i, 0) == NFe.get(j).getId_Nota_Fiscal()) {
                //     flag = false;
                //     System.out.println("é igual!");
                // }

                //}
                //if (flag) {
                // System.out.println("é diferente!");
                modeloNFe.addRow(new Object[]{NFe.get(i).getId_Nota_Fiscal(), NFe.get(i).getTextoCliente(), NFe.get(i).getTextoLogradouro(), NFe.get(i).getTextoCidade(), NFe.get(i).getTextoEstado()});
            }

        } catch (SQLException ex) {
            Logger.getLogger(InternalCargas.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoPesquisarActionPerformed

    public void setarCampos() throws SQLException {
        DefaultComboBoxModel modelCidades = new DefaultComboBoxModel(itensCidades);
        cidadeComboBox.setModel(modelCidades);

        DefaultComboBoxModel modelTransportador = new DefaultComboBoxModel(itensTransportador);
        transporteComboBox.setModel(modelTransportador);

        idCargaNum.setText(Integer.toString(cargasDAO.numCarga()));
        idRotaNum.setText(Integer.toString(cargasDAO.numRota()));

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idCargaNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCargaNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCargaNumActionPerformed

    private void botaoConfirmarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCargaActionPerformed

        int linha = tabelaCargas.getRowCount();
        CargasGetSet Carga = new CargasGetSet();
        List cidades_entrega = new ArrayList();
      
        for (int i = 0; i < linha; i++) {
            Carga.setNFe(Integer.parseInt(tabelaCargas.getValueAt(i, 0).toString()));
            cidades_entrega.add(tabelaCargas.getValueAt(i, 3).toString());
            
            try {
                cargasDAO.insertCargas(Carga);
            } catch (SQLException ex) {
                Logger.getLogger(InternalCargas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        Carga.setCidades_entrega(cidades_entrega);
        
       
        
        modeloCargas.setNumRows(0);
        
    }//GEN-LAST:event_botaoConfirmarCargaActionPerformed

    private void idRotaNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRotaNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRotaNumActionPerformed

    private void transporteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transporteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transporteComboBoxActionPerformed

    private void tabelaNFRelacionadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNFRelacionadaMouseClicked

    }//GEN-LAST:event_tabelaNFRelacionadaMouseClicked

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed

        int linha = tabelaNFRelacionada.getSelectedRow();
        modeloCargas = (DefaultTableModel) tabelaCargas.getModel();
        modeloNFe = (DefaultTableModel) tabelaNFRelacionada.getModel();
        if (linha != -1) {
            modeloCargas.addRow(new Object[]{tabelaNFRelacionada.getValueAt(linha, 0), tabelaNFRelacionada.getValueAt(linha, 1), tabelaNFRelacionada.getValueAt(linha, 2), tabelaNFRelacionada.getValueAt(linha, 3), tabelaNFRelacionada.getValueAt(linha, 4)});
            modeloNFe.removeRow(linha);

            //modeloCargas.addRow((Object[]{tabelaNFRelacionada.getValueAt(linha, 0)}));
//            NFeGetSet nfegs = new NFeGetSet();
//            
//            nfegs.setId_Nota_Fiscal(Integer.parseInt(modeloCargas.getValueAt(linha, 0).toString()));
//            nfegs.setTextoCliente(modeloCargas.getValueAt(linha, 1).toString());
//            nfegs.setTextoLogradouro(modeloCargas.getValueAt(linha, 2).toString());
//            nfegs.setTextoCidade(modeloCargas.getValueAt(linha, 3).toString());
//            nfegs.setTextoEstado(modeloCargas.getValueAt(linha, 4).toString());
//            System.out.println(nfegs);
//           
//            modeloCargas.addRow(new Object[]{nfegs.getId_Nota_Fiscal(), nfegs.getTextoCliente(), nfegs.getTextoLogradouro(), nfegs.getTextoCidade(), nfegs.getTextoEstado()});
//            modeloNFe.removeRow(linha);
//            tabelaNFRelacionada.setModel(modeloNFe);
//            tabelaCargas.setModel(modeloCargas);
        }


    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBaixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBaixoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoBaixo;
    private javax.swing.JButton botaoCima;
    private javax.swing.JButton botaoConfirmarCarga;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JComboBox<String> cidadeComboBox;
    private javax.swing.JTextField idCargaNum;
    private javax.swing.JTextField idRotaNum;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelaCargas;
    private javax.swing.JTable tabelaNFRelacionada;
    private javax.swing.JComboBox<String> transporteComboBox;
    // End of variables declaration//GEN-END:variables
}
