/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CargasDAO;
import gets_sets.CargasGetSet;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp16
 */
public class InternalVisualizarCargas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalVisualizarCargas
     */
    private CargasDAO cargasDAO = new CargasDAO();
    List<CargasGetSet> CargasGS = null;
    private DefaultTableModel modeloCargas;

    public InternalVisualizarCargas() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void setarCampos() throws SQLException {

         
            CargasGS = cargasDAO.getCargas();
        


        modeloCargas = (DefaultTableModel) tabelaCargas.getModel();

        for (int i = 0; i < CargasGS.size(); i++) {

            modeloCargas.addRow(new Object[]{CargasGS.get(i).getIdCarga(), CargasGS.get(i).getId_Nota_Fiscal(), CargasGS.get(i).getCliente(), CargasGS.get(i).getDescPedido(), CargasGS.get(i).getCidade()});
        }

        tabelaCargas.setModel(modeloCargas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCargas = new javax.swing.JTable();
        botaoFechar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cargas Disponíveis");

        tabelaCargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Carga", "NFe", "Cliente", "Item", "Cidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaCargas);

        botaoFechar.setText("Sair");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botaoFechar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_botaoFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCargas;
    // End of variables declaration//GEN-END:variables
}
