/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import dao.CargasDAO;
import dao.nfeDAO;
import dao.rotasDAO;
import gets_sets.NFeGetSet;
import gets_sets.RotasGetSet;
import gets_sets.TransportadorGetSet;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wesley Ricardo
 */
public class InternalRotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalRotas
     */
    private final InternalCargas int_cargas = new InternalCargas();
    private DefaultTableModel modeloRotas;

    
    private nfeDAO nfeDAO = new nfeDAO();
    private DefaultTableModel modeloItensNota;
    List<NFeGetSet> NFeGS = null;
    List<TransportadorGetSet> transGS;
    private rotasDAO rotasDAO = new rotasDAO();
    
    public InternalRotas() {
        initComponents();

    }

    public void setarCampos() throws SQLException {

        Vector itensTransportador = rotasDAO.carregaTransportador();
        //List<RotasGetSet> rotas = rotasdao.listarCargasLiberadas(comboTransportador.getSelectedItem().toString());
        
        DefaultComboBoxModel modeloTransportador = new DefaultComboBoxModel(itensTransportador);
        comboTransportador.setModel(modeloTransportador);

        modeloRotas = (DefaultTableModel) tabelaRotas.getModel();  

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRotas = new javax.swing.JTable();
        comboTransportador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        botaoVisualizar = new javax.swing.JButton();
        botaoEncerrar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setClosable(true);

        tabelaRotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Carga", "Cidades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaRotas);
        if (tabelaRotas.getColumnModel().getColumnCount() > 0) {
            tabelaRotas.getColumnModel().getColumn(0).setResizable(false);
            tabelaRotas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelaRotas.getColumnModel().getColumn(1).setResizable(false);
            tabelaRotas.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        comboTransportador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTransportador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboTransportadorMouseExited(evt);
            }
        });
        comboTransportador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTransportadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Transportador");

        comboVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veículo" }));

        jLabel2.setText("Veículo");

        botaoVisualizar.setText("Visualizar");
        botaoVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarActionPerformed(evt);
            }
        });

        botaoEncerrar.setText("Encerrar Carga");
        botaoEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncerrarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTransportador, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botaoVisualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(botaoEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTransportador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botaoVisualizar)))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEncerrar)
                    .addComponent(botaoCancelar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTransportadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTransportadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTransportadorActionPerformed

    private void comboTransportadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTransportadorMouseExited

        Vector itensVeiculos = null;
        try {
            itensVeiculos = rotasDAO.carregaVeiculos(comboTransportador.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(InternalRotas.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultComboBoxModel modeloVeiculo = new DefaultComboBoxModel(itensVeiculos);
        comboVeiculo.setModel(modeloVeiculo);

    }//GEN-LAST:event_comboTransportadorMouseExited

    private void botaoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarActionPerformed
        
        
        modeloRotas.setNumRows(0);
        try {
            String transporte = (String) comboTransportador.getSelectedItem();
            String veiculo = (String) comboVeiculo.getSelectedItem();

            List<RotasGetSet> listaRotas = rotasDAO.getRotas(transporte, veiculo);
           
            modeloRotas = (DefaultTableModel) tabelaRotas.getModel();

            for (int i = 0; i < listaRotas.size(); i++) {
     
                modeloRotas.addRow(new Object[]{listaRotas.get(i).getIdCarga(), listaRotas.get(i).getListaCidadeString(), listaRotas.get(i).getIdRota()});
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(InternalRotas.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_botaoVisualizarActionPerformed

    private void botaoEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncerrarActionPerformed
        
        int linha = tabelaRotas.getSelectedRow();
        Integer idCarga = Integer.parseInt(tabelaRotas.getValueAt(linha, 0).toString());
        
        try {
            rotasDAO.atualizarCarga(idCarga);
        } catch (SQLException ex) {
            Logger.getLogger(InternalRotas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        modeloRotas.removeRow(linha);
        
        tabelaRotas.setModel(modeloRotas);
        
        
    }//GEN-LAST:event_botaoEncerrarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_botaoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoEncerrar;
    private javax.swing.JButton botaoVisualizar;
    private javax.swing.JComboBox<String> comboTransportador;
    private javax.swing.JComboBox<String> comboVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRotas;
    // End of variables declaration//GEN-END:variables
}
