/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import dao.CargasDAO;
import dao.rotasDAO;
import gets_sets.NFeGetSet;
import gets_sets.RotasGetSet;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wesley Ricardo
 */
public class InternalRotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalRotas
     */
    private final InternalCargas int_cargas = new InternalCargas();
    private DefaultTableModel modeloRotas;

    rotasDAO rotasdao = new rotasDAO();

    public InternalRotas() {
        initComponents();

    }

    public void setarCampos() throws SQLException {

        Vector itensTransportador = rotasdao.carregaTransportador();
        //List<RotasGetSet> rotas = rotasdao.listarCargasLiberadas(comboTransportador.getSelectedItem().toString());
        
        DefaultComboBoxModel modeloTransportador = new DefaultComboBoxModel(itensTransportador);
        comboTransportador.setModel(modeloTransportador);

        modeloRotas = (DefaultTableModel) tabelaRotas.getModel();  

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRotas = new javax.swing.JTable();
        comboTransportador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        tabelaRotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Identificação", "Cidades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaRotas);
        if (tabelaRotas.getColumnModel().getColumnCount() > 0) {
            tabelaRotas.getColumnModel().getColumn(0).setResizable(false);
            tabelaRotas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelaRotas.getColumnModel().getColumn(1).setResizable(false);
            tabelaRotas.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        comboTransportador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTransportador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboTransportadorMouseExited(evt);
            }
        });
        comboTransportador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTransportadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Transportador");

        comboVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veículo" }));

        jLabel2.setText("Veículo");

        jLabel3.setText("Carga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTransportador, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTransportador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTransportadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTransportadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTransportadorActionPerformed

    private void comboTransportadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTransportadorMouseExited

        Vector itensVeiculos = null;
        try {
            itensVeiculos = rotasdao.carregaVeiculos(comboTransportador.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(InternalRotas.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultComboBoxModel modeloVeiculo = new DefaultComboBoxModel(itensVeiculos);
        comboVeiculo.setModel(modeloVeiculo);

    }//GEN-LAST:event_comboTransportadorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTransportador;
    private javax.swing.JComboBox<String> comboVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRotas;
    // End of variables declaration//GEN-END:variables
}
